name: "Check DL WB Python wrapper with Pylint and Bandit"

on: [push, pull_request]

jobs:

  check-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install bandit==1.7.0 pylint==2.8.3
          python -m pip install -r starting_package/requirements-core.txt
          python -m pip install -r starting_package/requirements-linux.txt
      - name: Run lint check
        run: |
          export PYTHONPATH=${PYTHONPATH}:starting_package
          pylint --rcfile=automation/.pylintrc starting_package
      - name: Create a temporary artifact folder for the Bandit scan
        run: mkdir artifacts

      - name: Run Bandit check
        run: |
          bandit -r starting_package -o artifacts/bandit_check.txt -f txt
      - name: Upload Bandit artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bandit-artifacts
          path: artifacts
